#import <Foundation/Foundation.h>

#import "DingiFoundation.h"

/// Project version number for Mapbox.
FOUNDATION_EXPORT MGL_EXPORT double DingiMapVersionNumber;

/// Project version string for Mapbox.
FOUNDATION_EXPORT MGL_EXPORT const unsigned char DingiMapVersionString[];

#import "DingiAnnotationView.h"
#import "DingiAccountManager.h"
#import "DingiAnnotation.h"
#import "DingiAnnotationImage.h"
#import "DingiCalloutView.h"
#import "DingiClockDirectionFormatter.h"
#import "DingiCompassDirectionFormatter.h"
#import "DingiCoordinateFormatter.h"
#import "DingiDistanceFormatter.h"
#import "DingiFeature.h"
#import "DingiGeometry.h"
#import "DingiLight.h"
#import "DingiMapCamera.h"
#import "DingiMapView.h"
#import "DingiMapView+IBAdditions.h"
#import "DingiMapViewDelegate.h"
#import "DingiMultiPoint.h"
#import "DingiOfflinePack.h"
#import "DingiOfflineRegion.h"
#import "DingiOfflineStorage.h"
#import "DingiOverlay.h"
#import "DingiPointAnnotation.h"
#import "DingiPointCollection.h"
#import "DingiPolygon.h"
#import "DingiPolyline.h"
#import "DingiShape.h"
#import "DingiShapeCollection.h"
#import "DingiStyle.h"
#import "DingiStyleLayer.h"
#import "DingiForegroundStyleLayer.h"
#import "DingiVectorStyleLayer.h"
#import "DingiFillExtrusionStyleLayer.h"
#import "DingiFillStyleLayer.h"
#import "DingiLineStyleLayer.h"
#import "DingiSymbolStyleLayer.h"
#import "DingiRasterStyleLayer.h"
#import "DingiCircleStyleLayer.h"
#import "DingiHeatmapStyleLayer.h"
#import "DingiHillshadeStyleLayer.h"
#import "DingiBackgroundStyleLayer.h"
#import "DingiOpenGLStyleLayer.h"
#import "DingiSource.h"
#import "DingiTileSource.h"
#import "DingiVectorTileSource.h"
#import "DingiShapeSource.h"
#import "DingiComputedShapeSource.h"
#import "DingiRasterTileSource.h"
#import "DingiRasterDEMSource.h"
#import "DingiImageSource.h"
#import "DingiShapeOfflineRegion.h"
#import "DingiTilePyramidOfflineRegion.h"
#import "DingiTypes.h"
#import "DingiUserLocation.h"
#import "DingiUserLocationAnnotationView.h"
#import "NSValue+MGLAdditions.h"
#import "MGLStyleValue.h"
#import "DingiAttributionInfo.h"
#import "DingiMapSnapshotter.h"
#import "NSExpression+MGLAdditions.h"
#import "NSPredicate+MGLAdditions.h"
#import "DingiLocationManager.h"
#import "DingiLoggingConfiguration.h"
